### ISSUE TITLE
[BaseTools] EfiLdrImage : a segmentation fault from vfprintf() (Bugzilla Bug 533)

### ISSUE THREAD

**Issue by tianocore-issues** [tianocore/edk2#6980]
This issue was created automatically with [bugzilla2github](https://github.com/makubacki/bugzilla2github/tree/bz2gh_tianocore)
# Bugzilla Bug 533
Date: 2017-05-12T15:38:21+00:00
From: Bo Chen &lt;<chenbo>&gt;
To:   Yonghong Zhu &lt;<yonghong.zhu>&gt;
CC:   ye.y.wu, yonghong.zhu

Last updated: 2017-07-31T22:57:08+00:00

**Comment by tianocore-issues** [comment]
## Comment 2030
Date: 2017-05-12 15:38:21 +0000
From: Bo Chen &lt;<chenbo>&gt;

- Industry Specification: ---
- Target OS: ---
- Bugzilla Assignee(s): Yonghong Zhu &lt;<yonghong.zhu>&gt;

===================
Details of the Bug
===================

--------------
EDK2 Revision:
--------------
75ce7ef7cf054e1a266ae0e54c19a1ab66d80c6e

(Also can be reproduced with the latest revision at this time.)

--------------------
Platform &amp; Compiler:
--------------------
Ubuntu 14.04.5 LTS
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4

------------
Cmmand-line:
------------
./EfiLdrImage &apos;-V%n%a&apos;

--------------------
GBD log:
--------------------

GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later &lt;http://gnu.org/licenses/gpl.html&gt;
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type &quot;show copying&quot;
and &quot;show warranty&quot; for details.
This GDB was configured as &quot;x86_64-linux-gnu&quot;.
Type &quot;show configuration&quot; for configuration details.
For bug reporting instructions, please see:
&lt;http://www.gnu.org/software/gdb/bugs/&gt;.
Find the GDB manual and other documentation resources online at:
&lt;http://www.gnu.org/software/gdb/documentation/&gt;.
For help, type &quot;help&quot;.
Type &quot;apropos word&quot; to search for commands related to &quot;word&quot;.

Program received signal SIGSEGV, Segmentation fault.
0x00002aaaaad1e327 in _IO_vfprintf_internal (s=s@entry=0x7fffffffd070, format=&lt;optimized out&gt;, format@entry=0x7fffffffecc7 &quot;-V%n%a&quot;, 
    ap=ap@entry=0x7fffffffd638) at vfprintf.c:1660
1660	vfprintf.c: No such file or directory.
(gdb) bt
#0  0x00002aaaaad1e327 in _IO_vfprintf_internal (s=s@entry=0x7fffffffd070, format=&lt;optimized out&gt;, format@entry=0x7fffffffecc7 &quot;-V%n%a&quot;, 
    ap=ap@entry=0x7fffffffd638) at vfprintf.c:1660
#1  0x00002aaaaad408fb in __IO_vsprintf (string=0x7fffffffd1e0 &quot;-VERROR 1003&quot;, format=0x7fffffffecc7 &quot;-V%n%a&quot;, args=0x7fffffffd638)
    at iovsprintf.c:42
#2  0x0000000000403e53 in PrintMessage (Type=0x407ff8 &quot;ERROR&quot;, FileName=0x0, LineNumber=0, MessageCode=1003, 
    Text=0x407cd8 &quot;Invalid option value&quot;, MsgFmt=0x7fffffffecc7 &quot;-V%n%a&quot;, List=0x7fffffffd638) at EfiUtilityMsgs.c:523
#3  0x00000000004032b0 in Error (FileName=0x0, LineNumber=0, MessageCode=1003, Text=0x407cd8 &quot;Invalid option value&quot;, 
    MsgFmt=0x7fffffffecc7 &quot;-V%n%a&quot;) at EfiUtilityMsgs.c:132
#4  0x0000000000401c15 in main (argc=1, argv=0x7fffffffea40) at EfiLdrImage.c:224

**Comment by tianocore-issues** [comment]
## Comment 2276
Date: 2017-06-15 04:35:37 +0000
From: Yonghong Zhu &lt;<yonghong.zhu>&gt;

change Package from N/A to BaseTools

**Comment by tianocore-issues** [comment]
## Comment 2369
Date: 2017-06-28 21:07:35 +0000
From: Chris &lt;<ye.y.wu>&gt;

assign to Yonghong for investigation firstly

**Comment by tianocore-issues** [comment]
## Comment 2473
Date: 2017-07-19 21:17:29 +0000
From: Yonghong Zhu &lt;<yonghong.zhu>&gt;

Assign to Yonghong to fix.

**Comment by tianocore-issues** [comment]
## Comment 2537
Date: 2017-07-31 22:57:08 +0000
From: Yonghong Zhu &lt;<yonghong.zhu>&gt;

push the fix SHA-1: b5bd6387d225dfef9a693982cabccd37fcdd1fb7
