### ISSUE TITLE
CryptoPkg: RsaGetPrivateKeyFromPem() crashed in Libfuzzer test (Bugzilla Bug 4075)

### ISSUE THREAD

**Issue by tianocore-issues** [tianocore/edk2#9208]
This issue was created automatically with [bugzilla2github](https://github.com/makubacki/bugzilla2github/tree/bz2gh_tianocore)
# Bugzilla Bug 4075
Date: 2022-09-21T04:06:25+00:00
From: @liyi77
To:   unassigned &lt;<unassigned>&gt;
CC:   yi1.li

Last updated: 2022-09-26T07:54:25+00:00

**Comment by tianocore-issues** [comment]
## Comment 19600
Date: 2022-09-21 04:06:25 +0000
From: @liyi77

- Industry Specification: ---
- Release Observed: EDK II Master
- Releases to Fix: EDK II Master
- Target OS: ---
- Bugzilla Assignee(s): unassigned &lt;<unassigned>&gt;

Used Libfuzzer (clang+llvm-11.0.0) as the fuzzer,based on HBFA.

Test case: https://github.com/liyi77/edk2-staging/blob/HBFA/HBFA/UefiHostFuzzTestCasePkg/TestCase/CryptoPkg/Pem/TestPem.c

Log:
/home/liyi4/wpa3fuzz/Build/UefiHostFuzzTestCryptoPkg/DEBUG_LIBFUZZER/X64/TestPem: Running 1 inputs 1 time(s) each.
Running: /home/liyi4/wpa3fuzz/TlsSetKeySeed/crash2
=================================================================
==13339==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x603000000471 at pc 0x000000557b67 bp 0x7fffffffce20 sp 0x7fffffffce18
READ of size 1 at 0x603000000471 thread T0
    #0 0x557b66 in AsciiStrnLenS /home/liyi4/wpa3fuzz/edk2-staging/HBFA/UefiHostTestPkg/Library/BaseLibHost/SafeString.c:1772:10
    #1 0x591427 in OBJ_obj2txt /home/liyi4/wpa3fuzz/edk2/CryptoPkg/Library/OpensslLib/openssl/crypto/objects/obj_dat.c:486:17
    #2 0x6109e2 in i2t_ASN1_OBJECT /home/liyi4/wpa3fuzz/edk2/CryptoPkg/Library/OpensslLib/openssl/crypto/asn1/a_object.c:182:12
    #3 0x6a3d9b in EVP_PKCS82PKEY /home/liyi4/wpa3fuzz/edk2/CryptoPkg/Library/OpensslLib/openssl/crypto/evp/evp_pkey.c:37:9
    #4 0x599a52 in PEM_read_bio_PrivateKey /home/liyi4/wpa3fuzz/edk2/CryptoPkg/Library/OpensslLib/openssl/crypto/pem/pem_pkey.c:45:15
    #5 0x594477 in PEM_read_bio_RSAPrivateKey /home/liyi4/wpa3fuzz/edk2/CryptoPkg/Library/OpensslLib/openssl/crypto/pem/pem_all.c:67:13
    #6 0x54fb17 in RsaGetPrivateKeyFromPem /home/liyi4/wpa3fuzz/edk2/CryptoPkg/Library/BaseCryptLib/Pem/CryptPem.c:116:17
    #7 0x54dea0 in RunTestHarness /home/liyi4/wpa3fuzz/edk2-staging/HBFA/UefiHostFuzzTestCasePkg/TestCase/CryptoPkg/Pem/TestPem.c:72:7
    #8 0x54dbf7 in LLVMFuzzerTestOneInput /home/liyi4/wpa3fuzz/edk2-staging/HBFA/UefiHostFuzzTestPkg/Library/ToolChainHarnessLib/ToolChainHarnessLib.c:138:3
    #9 0x4586e1 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/home/liyi4/wpa3fuzz/Build/UefiHostFuzzTestCryptoPkg/DEBUG_LIBFUZZER/X64/TestPem+0x4586e1)
    #10 0x443e52 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) (/home/liyi4/wpa3fuzz/Build/UefiHostFuzzTestCryptoPkg/DEBUG_LIBFUZZER/X64/TestPem+0x443e52)
    #11 0x449906 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/home/liyi4/wpa3fuzz/Build/UefiHostFuzzTestCryptoPkg/DEBUG_LIBFUZZER/X64/TestPem+0x449906)
    #12 0x4725c2 in main (/home/liyi4/wpa3fuzz/Build/UefiHostFuzzTestCryptoPkg/DEBUG_LIBFUZZER/X64/TestPem+0x4725c2)
    #13 0x7ffff7a6d082 in __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16
    #14 0x41e51d in _start (/home/liyi4/wpa3fuzz/Build/UefiHostFuzzTestCryptoPkg/DEBUG_LIBFUZZER/X64/TestPem+0x41e51d)

0x603000000471 is located 0 bytes to the right of 17-byte region [0x603000000460,0x603000000471)
allocated by thread T0 here:
    #0 0x51e24d in malloc (/home/liyi4/wpa3fuzz/Build/UefiHostFuzzTestCryptoPkg/DEBUG_LIBFUZZER/X64/TestPem+0x51e24d)
    #1 0x57ffdf in CRYPTO_malloc /home/liyi4/wpa3fuzz/edk2/CryptoPkg/Library/OpensslLib/openssl/crypto/mem.c:222:11
    #2 0x655290 in BN_bn2dec /home/liyi4/wpa3fuzz/edk2/CryptoPkg/Library/OpensslLib/openssl/crypto/bn/bn_print.c:73:11
    #3 0x59140a in OBJ_obj2txt /home/liyi4/wpa3fuzz/edk2/CryptoPkg/Library/OpensslLib/openssl/crypto/objects/obj_dat.c:483:21
    #4 0x6109e2 in i2t_ASN1_OBJECT /home/liyi4/wpa3fuzz/edk2/CryptoPkg/Library/OpensslLib/openssl/crypto/asn1/a_object.c:182:12
    #5 0x6a3d9b in EVP_PKCS82PKEY /home/liyi4/wpa3fuzz/edk2/CryptoPkg/Library/OpensslLib/openssl/crypto/evp/evp_pkey.c:37:9
    #6 0x599a52 in PEM_read_bio_PrivateKey /home/liyi4/wpa3fuzz/edk2/CryptoPkg/Library/OpensslLib/openssl/crypto/pem/pem_pkey.c:45:15
    #7 0x594477 in PEM_read_bio_RSAPrivateKey /home/liyi4/wpa3fuzz/edk2/CryptoPkg/Library/OpensslLib/openssl/crypto/pem/pem_all.c:67:13
    #8 0x54fb17 in RsaGetPrivateKeyFromPem /home/liyi4/wpa3fuzz/edk2/CryptoPkg/Library/BaseCryptLib/Pem/CryptPem.c:116:17
    #9 0x54dea0 in RunTestHarness /home/liyi4/wpa3fuzz/edk2-staging/HBFA/UefiHostFuzzTestCasePkg/TestCase/CryptoPkg/Pem/TestPem.c:72:7

**Comment by tianocore-issues** [comment]
## Comment 19601
Date: 2022-09-21 04:07:36 +0000
From: @liyi77

Created attachment 1026
crash seed

Attachment: [BZ-1026-crash2](https://github.com/tianocore/user-attachments/raw/refs/heads/main/tianocore/edk2/BZ-1026-crash2)

**Comment by tianocore-issues** [comment]
## Comment 19602
Date: 2022-09-21 04:08:11 +0000
From: @liyi77

The root cause is the inappropriate implementation of BIO_snprintf():
https://github.com/tianocore/edk2/blob/2c17d676e402d75a3a674499342f7ddaccf387bd/CryptoPkg/Library/BaseCryptLib/SysCall/CrtWrapper.c#L489-L498 
For the crashed case, RsaGetPrivateKeyFromPem() will:
1)malloc a piece of memory S,
(edk2/CryptoPkg/Library/OpensslLib/openssl/crypto/bn/bn_print.c:73:11)

2)and use BIO_snprintf() to print a NULL-terminated string to S,
(edk2/CryptoPkg/Library/OpensslLib/openssl/crypto/bn/bn_print.c:104:11)

3)finally call strlen(S) to get length.
(edk2/CryptoPkg/Library/OpensslLib/openssl/crypto/objects/obj_dat.c:486:17)

Due to BIO_snprintf() does nothing but just return a good status 0, program will consider this string to be written successfully, then strlen() will heap-buffer-overflow.

There are two solution choice:
	1. Add true implementation to OpensslLib, but this will increase the 8kb DXE driver binary size.
	https://github.com/tianocore/edk2/pull/3361
	2. Fake BIO_snprintf() need to return error status -1.
https://github.com/tianocore/edk2/pull/3360

**Comment by tianocore-issues** [comment]
## Comment 19610
Date: 2022-09-22 03:52:14 +0000
From: @liyi77

&gt; There are two solution choice:
&gt; 	1. Add true implementation to OpensslLib, but this will increase the 8kb
&gt; DXE driver binary size.
&gt; 	https://github.com/tianocore/edk2/pull/3361
&gt; 	2. Fake BIO_snprintf() need to return error status -1.
&gt; https://github.com/tianocore/edk2/pull/3360

Solution 1 need to turn on SSE when use GCC, it will be huge impact.

Recommend solution2.

**Comment by tianocore-issues** [comment]
## Comment 19612
Date: 2022-09-23 00:36:41 +0000
From: @liyi77

Patch sent.
https://edk2.groups.io/g/devel/message/94119

**Comment by tianocore-issues** [comment]
## Comment 19630
Date: 2022-09-26 07:54:25 +0000
From: @liyi77

Merged https://github.com/tianocore/edk2/pull/3401
